// Examen d'admission — Français — PFEQ Québec
// Pool : 70 questions (50 originales + 20 IA) · tirage aléatoire de 50 · 30 minutes
var EXAM_FR_POOL=[

  // ── PRODUCTION ÉCRITE ────────────────────────────────────────────
  {q:"Dans quelle partie d'une <strong>production écrite</strong> écrirais-tu cette phrase&nbsp;? «&nbsp;Je vais vous parler de ma première journée de camping.&nbsp;»",choices:["Situation de départ ou introduction","Élément déclencheur","Péripéties","Situation finale ou conclusion"],answer:"Situation de départ ou introduction",sol:"Une phrase qui annonce le thème correspond à la situation de départ ou introduction."},
  {q:"Dans quelle partie d'une <strong>production écrite</strong> place-t-on l'événement qui bouleverse la situation initiale&nbsp;?",choices:["Situation de départ","Élément déclencheur","Situation finale","Péripéties"],answer:"Élément déclencheur",sol:"L'élément déclencheur est l'événement qui rompt l'équilibre de départ et lance l'action.",ai:true},

  // ── STRUCTURE DE LA PHRASE ────────────────────────────────────────
  {q:"«&nbsp;Une phrase de base <strong>bien structurée</strong> comprend…&nbsp;»",choices:["…un groupe du nom et un complément de phrase.","…un pronom personnel sujet et un attribut.","…un groupe sujet et un groupe du verbe.","…un groupe du verbe et un complément de phrase."],answer:"…un groupe sujet et un groupe du verbe.",sol:"La phrase de base minimale contient un groupe sujet (GS) et un groupe du verbe (GV)."},

  // ── TYPE DE PHRASE ────────────────────────────────────────────────
  {q:"De quel <strong>type</strong> est cette phrase&nbsp;? «&nbsp;Les tartes aux pommes que fait ma grand-mère sont les meilleures au monde.&nbsp;»",choices:["Exclamative","Interrogative","Déclarative","Impérative"],answer:"Déclarative",sol:"Cette phrase énonce un fait et se termine par un point → déclarative."},
  {q:"De quel <strong>type</strong> est cette phrase&nbsp;? «&nbsp;Range ta chambre immédiatement&nbsp;!&nbsp;»",choices:["Déclarative","Interrogative","Impérative","Exclamative"],answer:"Impérative",sol:"Cette phrase exprime un ordre adressé à quelqu'un → impérative.",ai:true},
  {q:"Laquelle de ces phrases est une <strong>phrase interrogative</strong>&nbsp;?",choices:["Les chiens sont très fidèles.","Amélie donne-t-elle un spectacle ce soir&nbsp;?","Je vais à mon cours de judo.","Mon cousin a eu un accident de ski."],answer:"Amélie donne-t-elle un spectacle ce soir&nbsp;?",sol:"La phrase interrogative pose une question ; elle se termine par un point d'interrogation et peut utiliser l'inversion du sujet."},

  // ── PONCTUATION ───────────────────────────────────────────────────
  {q:"Une phrase ci-dessous contient une <strong>erreur de ponctuation</strong>. Laquelle&nbsp;?",choices:["Plusieurs insectes sont très utiles.","Ce reptile est-il dangereux&nbsp;?","Comme le temps passe vite.","Je ne ferai pas ma recherche sur les araignées."],answer:"Comme le temps passe vite.",sol:"«&nbsp;Comme le temps passe vite&nbsp;» est une phrase exclamative ; elle devrait se terminer par un point d'exclamation (!), non par un point."},
  {q:"Complète les phrases suivantes avec les <strong>signes de ponctuation</strong> appropriés. «&nbsp;J'ai fini mes devoirs _ j'ai ramassé ma chambre et j'ai pratiqué mon piano. Qui dit mieux _&nbsp;»",choices:[". et ?","; et !",": et ?",", et ?"],answer:"; et !",sol:"Le point-virgule sépare deux propositions indépendantes liées. «&nbsp;Qui dit mieux&nbsp;!&nbsp;» est exclamatif."},
  {q:"Combien de <strong>virgules</strong> doit-on écrire dans la phrase suivante&nbsp;? «&nbsp;Veux-tu des fraises des kiwis des framboises des bleuets ou des mûres&nbsp;?&nbsp;»",choices:["une","deux","trois","quatre"],answer:"trois",sol:"On sépare les éléments d'une énumération par des virgules sauf avant «&nbsp;ou&nbsp;» : fraises, kiwis, framboises, bleuets ou des mûres → 3 virgules."},
  {q:"Dans quelle phrase l'utilisation du <strong>deux-points</strong> (:) est-elle correcte&nbsp;?",choices:["Je suis fatigué : car j'ai mal dormi.","Il a dit : «&nbsp;Bonne chance&nbsp;!&nbsp;»","Le problème est : difficile à résoudre.","Je veux : une pomme."],answer:"Il a dit : «&nbsp;Bonne chance&nbsp;!&nbsp;»",sol:"Le deux-points introduit une citation ou un discours direct. Il ne s'emploie pas devant «&nbsp;car&nbsp;» ni directement devant un adjectif ou un simple complément.",ai:true},

  // ── GROUPES GRAMMATICAUX ──────────────────────────────────────────
  {q:"Combien y a-t-il de <strong>groupes du nom</strong> dans la phrase suivante&nbsp;? «&nbsp;Louise mange un bon yogourt à la vanille bien frais.&nbsp;»",choices:["un","deux","trois","quatre"],answer:"trois",sol:"GN : 1.&nbsp;Louise (sujet) 2.&nbsp;un bon yogourt à la vanille bien frais (CD) 3.&nbsp;la vanille (à l'intérieur du GPrép «&nbsp;à la vanille&nbsp;»)."},
  {q:"Quel est le <strong>groupe du verbe</strong> de cette phrase&nbsp;? «&nbsp;Ce magicien nous a démontré son savoir-faire.&nbsp;»",choices:["Ce magicien nous a démontré","a démontré","nous a démontré son savoir-faire","a démontré son savoir-faire"],answer:"nous a démontré son savoir-faire",sol:"Le GV comprend le verbe et tous ses compléments sauf le sujet : «&nbsp;nous a démontré son savoir-faire&nbsp;»."},
  {q:"À quel groupe, parmi les suivants, appartient un <strong>attribut du sujet</strong>&nbsp;?",choices:["Au groupe sujet","Au groupe complément de phrase","Au groupe du verbe","Au groupe prépositionnel"],answer:"Au groupe du verbe",sol:"L'attribut du sujet fait partie du GV ; il est relié au sujet par un verbe attributif (être, sembler, paraître…)."},
  {q:"Combien y a-t-il de <strong>groupes sujets</strong> dans cette phrase&nbsp;? «&nbsp;Es-tu certain que les juges nous accorderont une bonne note&nbsp;?&nbsp;»",choices:["un","deux","trois","quatre"],answer:"deux",sol:"Sujets : «&nbsp;tu&nbsp;» (inversé dans la question) et «&nbsp;les juges&nbsp;» (sujet de la subordonnée) → deux GS."},

  // ── FONCTIONS GRAMMATICALES ───────────────────────────────────────
  {q:"Quelle est la <strong>fonction</strong> du mot souligné de cette phrase&nbsp;? «&nbsp;Ton chien a l'air <u>malade</u>.&nbsp;»",choices:["Attribut du sujet","Complément du verbe (CD)","Complément de phrase","Sujet du verbe"],answer:"Attribut du sujet",sol:"«&nbsp;Malade&nbsp;» est relié au sujet «&nbsp;Ton chien&nbsp;» par le verbe d'état «&nbsp;avoir l'air&nbsp;» → attribut du sujet."},
  {q:"Quelle est la <strong>fonction</strong> du mot souligné de cette phrase&nbsp;? «&nbsp;Marie-Hélène <u>m'</u>a choisi dans son équipe.&nbsp;»",choices:["Sujet du verbe","Complément du verbe (CD)","Attribut du sujet","Complément de phrase"],answer:"Complément du verbe (CD)",sol:"«&nbsp;m'&nbsp;» = me, pronom CD du verbe «&nbsp;choisir&nbsp;» (elle a choisi qui ? → me)."},
  {q:"Quelle est la <strong>fonction</strong> du groupe de mots souligné de cette phrase&nbsp;? «&nbsp;<u>Après mes devoirs</u>, je vais faire un casse-tête.&nbsp;»",choices:["Attribut du sujet","Complément du verbe (CI)","Complément de phrase","Sujet du verbe"],answer:"Complément de phrase",sol:"«&nbsp;Après mes devoirs&nbsp;» est déplaçable et effaçable → complément de phrase."},
  {q:"Quelle est la <strong>fonction</strong> du mot souligné de cette phrase&nbsp;? «&nbsp;Sa marraine <u>lui</u> a acheté des pantoufles.&nbsp;»",choices:["Complément de phrase","Sujet du verbe","Complément du verbe (CI)","Attribut du sujet"],answer:"Complément du verbe (CI)",sol:"«&nbsp;lui&nbsp;» = à elle, pronom CI du verbe «&nbsp;acheter&nbsp;» (a acheté à qui ? → lui)."},

  // ── CLASSE DE MOTS ────────────────────────────────────────────────
  {q:"À quelle <strong>classe de mots</strong> appartiennent les mots soulignés des phrases suivantes&nbsp;? «&nbsp;J'aime <u>les</u> oiseaux. Je <u>les</u> observe souvent.&nbsp;»",choices:["Un déterminant et une préposition","Deux pronoms","Un déterminant et un pronom","Deux déterminants"],answer:"Un déterminant et un pronom",sol:"«&nbsp;les oiseaux&nbsp;» : les = déterminant défini. «&nbsp;Je les observe&nbsp;» : les = pronom personnel CD."},
  {q:"Parmi les mots soulignés suivants, lesquels sont des <strong>noms</strong>&nbsp;? «&nbsp;J'ai un <u>secret</u>¹ à te dire. Il a caché son trésor dans un lieu <u>secret</u>².&nbsp;» «&nbsp;Mon enseignant est <u>patient</u>³.&nbsp;» «&nbsp;Le <u>patient</u>⁴ est arrivé à l'heure.&nbsp;» «&nbsp;C'est un auteur <u>inconnu</u>⁵. Un <u>inconnu</u>⁶ frappe à la porte…&nbsp;»",choices:["1 – 2 – 4","2 – 4 – 5","1 – 3 – 6","1 – 4 – 6"],answer:"1 – 4 – 6",sol:"secret¹ (nom), patient⁴ (nom, sujet de «&nbsp;est arrivé&nbsp;»), inconnu⁶ (nom, sujet de «&nbsp;frappe&nbsp;») → 1, 4, 6."},
  {q:"Quel pronom n'est <strong>pas de la même classe</strong> que les autres&nbsp;?",choices:["quel","les nôtres","laquelle","lesquelles"],answer:"les nôtres",sol:"«&nbsp;les nôtres&nbsp;» est un pronom possessif. «&nbsp;quel&nbsp;», «&nbsp;laquelle&nbsp;» et «&nbsp;lesquelles&nbsp;» sont des pronoms interrogatifs ou relatifs."},
  {q:"Quel sens exprime l'<strong>adverbe souligné</strong> de la phrase suivante&nbsp;? «&nbsp;Ce soir, Marilou ira <u>peut-être</u> au cinéma.&nbsp;»",choices:["Un lieu","Une manière","Une affirmation","Un doute"],answer:"Un doute",sol:"«&nbsp;peut-être&nbsp;» exprime l'incertitude → adverbe de doute."},

  // ── CONJUGAISON ───────────────────────────────────────────────────
  {q:"Quel <strong>verbe conjugué</strong> doit compléter la phrase suivante&nbsp;? «&nbsp;Si tu le ________, on formerait une équipe du tonnerre.&nbsp;»",choices:["voudrais","voulais","voudras","veux"],answer:"voulais",sol:"Avec «&nbsp;si&nbsp;» + conditionnel présent dans la principale, la subordonnée prend l'imparfait. On n'emploie jamais le conditionnel après «&nbsp;si&nbsp;»."},
  {q:"Complète la phrase suivante avec les <strong>verbes conjugués</strong> appropriés. «&nbsp;_____-tu me prêter tes cartes de hockey si je te les _____ dès demain&nbsp;?&nbsp;»",choices:["Veux – rapportent","Veut – rapportent","Veux – rapporte","Veut – rapporte"],answer:"Veux – rapporte",sol:"Sujet «&nbsp;tu&nbsp;» → veux ; sujet «&nbsp;je&nbsp;» → rapporte."},
  {q:"Complète la phrase suivante avec les <strong>verbes conjugués</strong> appropriés. «&nbsp;La chasse aux trésors _____ et beaucoup _____ en trouver plus d'un.&nbsp;»",choices:["commence – espèrent","commencent – espère","commence – espère","commencent – espèrent"],answer:"commence – espèrent",sol:"«&nbsp;La chasse&nbsp;» (fém. sg.) → commence. «&nbsp;beaucoup&nbsp;» (pronom indéfini pluriel) → espèrent."},
  {q:"Complète la phrase suivante avec le <strong>groupe du verbe</strong> approprié. «&nbsp;Léa-Kim, sa sœur et moi _______.&nbsp;»",choices:["partent en camping","pars en camping","partez en camping","partons en camping"],answer:"partons en camping",sol:"«&nbsp;Léa-Kim, sa sœur et moi&nbsp;» équivaut à «&nbsp;nous&nbsp;» (1re pers. pl.) → partons."},
  {q:"Complète le mot avec la <strong>terminaison</strong> appropriée. «&nbsp;Noémie a invit___ ses amies pour son anniversaire.&nbsp;»",choices:["é","és","ées","er"],answer:"é",sol:"PP avec auxiliaire «&nbsp;avoir&nbsp;» ; le CD «&nbsp;ses amies&nbsp;» est placé après le verbe → pas d'accord → invité."},
  {q:"Complète le mot avec la <strong>terminaison</strong> appropriée. «&nbsp;Elles sont arriv___ tôt.&nbsp;»",choices:["é","és","ées","er"],answer:"ées",sol:"PP avec auxiliaire «&nbsp;être&nbsp;» → accord avec le sujet «&nbsp;Elles&nbsp;» (fém. pl.) → arrivées."},
  {q:"Complète le mot avec la <strong>terminaison</strong> appropriée. «&nbsp;Elles ont fait des jeux vari___.&nbsp;»",choices:["é","és","ées","er"],answer:"és",sol:"«&nbsp;jeux&nbsp;» est masculin pluriel → adjectif accordé : variés."},
  {q:"Complète le mot avec la <strong>terminaison</strong> appropriée. «&nbsp;Noémie a bien profit___ de sa journée.&nbsp;»",choices:["é","és","ées","er"],answer:"é",sol:"PP avec «&nbsp;avoir&nbsp;» ; le CD suit le verbe → pas d'accord → profité."},
  {q:"Complète le mot avec la <strong>terminaison</strong> appropriée. «&nbsp;Quelle chance de pouvoir s'amus___ avec des amies&nbsp;!&nbsp;»",choices:["é","és","ées","er"],answer:"er",sol:"Après «&nbsp;pouvoir&nbsp;», on emploie l'infinitif → amuser."},
  {q:"Complète le mot avec la <strong>terminaison</strong> appropriée. «&nbsp;…avec des amies aussi enjou___&nbsp;!&nbsp;»",choices:["é","és","ées","er"],answer:"ées",sol:"«&nbsp;enjouées&nbsp;» est un adjectif s'accordant avec «&nbsp;amies&nbsp;» (fém. pl.) → enjouées."},
  {q:"Dans quelle phrase les verbes sont-ils <strong>bien conjugués</strong>&nbsp;?",choices:["Il est temps que tu parte si tu veux arriver à temps.","Il est temps que tu partes si tu veux arriver à temps.","Il est temps que tu partes si tu veut arriver à temps.","Il est temps que tu partent si tu veux arriver à temps."],answer:"Il est temps que tu partes si tu veux arriver à temps.",sol:"«&nbsp;il est temps que&nbsp;» + subjonctif → «&nbsp;partes&nbsp;». «&nbsp;si tu&nbsp;» + indicatif présent → «&nbsp;veux&nbsp;»."},
  {q:"Parmi les verbes suivants, lequel pourrait être conjugué au <strong>présent</strong> ou au <strong>passé simple</strong> de l'indicatif&nbsp;?",choices:["comprit","jeta","obéit","crut"],answer:"obéit",sol:"«&nbsp;obéit&nbsp;» = présent (il obéit) OU passé simple (il obéit). Les autres ne sont possibles qu'au passé simple."},
  {q:"Trouve le <strong>mode et le temps</strong> de chaque verbe souligné de la phrase suivante. «&nbsp;<u>Ferme</u> la porte en <u>partant</u>.&nbsp;»",choices:["Indicatif présent, participe passé","Impératif présent, participe présent","Indicatif passé simple, participe présent","Impératif présent, participe passé"],answer:"Impératif présent, participe présent",sol:"«&nbsp;Ferme&nbsp;» = impératif présent (ordre). «&nbsp;partant&nbsp;» = participe présent (gérondif «&nbsp;en partant&nbsp;»)."},
  {q:"Complète la phrase suivante avec le verbe bien conjugué au <strong>futur simple</strong>. «&nbsp;Demain, nous _____ la forêt.&nbsp;»",choices:["explorerons","explorons","explorions","avons exploré"],answer:"explorerons",sol:"«&nbsp;Demain&nbsp;» indique le futur ; 1re pers. pl. → nous explorerons.",ai:true},

  // ── ACCORD ───────────────────────────────────────────────────────
  {q:"Quel <strong>pronom personnel</strong> remplace le groupe sujet de la phrase suivante&nbsp;? «&nbsp;La famille de Rose et Alexis fera une croisière l'été prochain.&nbsp;»",choices:["Il","Elle","Ils","Elles"],answer:"Elle",sol:"«&nbsp;La famille&nbsp;» est féminin singulier → elle."},
  {q:"Quels <strong>participes passés employés comme adjectifs</strong> complètent la phrase suivante&nbsp;? «&nbsp;Les ouvriers utilisent des techniques _______.&nbsp;»",choices:["spécialisée et varié","spécialisées et variée","spécialisés et variés","spécialisées et variées"],answer:"spécialisées et variées",sol:"«&nbsp;techniques&nbsp;» est féminin pluriel → spécialisées et variées."},
  {q:"Complète la phrase suivante avec l'<strong>attribut du sujet</strong> approprié. «&nbsp;Plusieurs automobiles et autobus semblent mal _______.&nbsp;»",choices:["stationné","stationnés","stationnées","stationnée"],answer:"stationnés",sol:"Le sujet mixte (féminin + masculin) prend le masculin pluriel → stationnés."},
  {q:"Complète la phrase suivante avec le <strong>déterminant</strong> et l'<strong>attribut du sujet</strong> appropriés. «&nbsp;_____ mes outils sont _____.&nbsp;»",choices:["Toutes – neufs","Tous – neuves","Tout – neufs","Tous – neufs"],answer:"Tous – neufs",sol:"«&nbsp;outils&nbsp;» est masculin pluriel → Tous mes outils sont neufs."},
  {q:"Complète la phrase suivante avec le <strong>participe passé</strong> approprié. «&nbsp;Les activités hivernales sont enfin _______.&nbsp;»",choices:["revenus","revenue","revenues","revenu"],answer:"revenues",sol:"Avec «&nbsp;être&nbsp;», le PP s'accorde avec le sujet : «&nbsp;les activités&nbsp;» = fém. pl. → revenues."},
  {q:"Complète avec le bon <strong>participe passé</strong>. «&nbsp;Les lettres que j'ai _____ sont sur le bureau.&nbsp;»",choices:["écrit","écrits","écrite","écrites"],answer:"écrites",sol:"PP avec «&nbsp;avoir&nbsp;» ; le CD «&nbsp;que&nbsp;» (= les lettres, fém. pl.) est placé avant le verbe → accord : écrites.",ai:true},
  {q:"Quelle phrase contient un <strong>accord d'adjectif</strong> correct&nbsp;?",choices:["Les élèves sont tous contentes.","Les élèves sont toutes contents.","Les élèves sont tous contents.","Les élèves sont tout contentes."],answer:"Les élèves sont tous contents.",sol:"Si «&nbsp;les élèves&nbsp;» est un groupe mixte ou masculin → tous (masc. pl.) et contents (masc. pl.).",ai:true},

  // ── GENRE ET NOMBRE ──────────────────────────────────────────────
  {q:"Parmi les mots suivants, lequel est <strong>féminin</strong>&nbsp;?",choices:["arc-en-ciel","aéroport","autobus","hygiène"],answer:"hygiène",sol:"L'hygiène est un nom féminin. Arc-en-ciel, aéroport et autobus sont masculins."},
  {q:"Parmi les mots suivants, lequel forme son <strong>féminin</strong> différemment des autres&nbsp;?",choices:["cadet","inquiet","muet","violet"],answer:"inquiet",sol:"cadet→cadette, muet→muette, violet→violette (double la consonne). Mais inquiet→inquiète (accent grave, sans doublement de t)."},
  {q:"Parmi les mots suivants, lequel est <strong>masculin</strong>&nbsp;?",choices:["atmosphère","estomac","horloge","épice"],answer:"estomac",sol:"L'estomac est masculin. L'atmosphère, l'horloge et l'épice sont féminins.",ai:true},
  {q:"Parmi les mots suivants, lequel forme son <strong>pluriel</strong> différemment des autres&nbsp;?",choices:["kangourou","caribou","joujou","filou"],answer:"joujou",sol:"joujou → joujoux (pluriel irrégulier en -x). Les autres forment leur pluriel en -s."},
  {q:"<strong>Vrai ou faux&nbsp;?</strong> Le pluriel de <em>tuyau, cheveu, amical</em> et <em>nouveau</em> est <em>tuyaux, cheveux, amicaux</em> et <em>nouveaux</em>.",choices:["Vrai","Faux"],answer:"Vrai",sol:"tuyaux ✓, cheveux ✓, amicaux ✓ (adjectif en -al → -aux), nouveaux ✓."},

  // ── MARQUEURS DE RELATION ─────────────────────────────────────────
  {q:"Complète la phrase suivante avec le <strong>marqueur de relation</strong> approprié. «&nbsp;Jeff se sauve, _____ il a peur du chien.&nbsp;»",choices:["donc","car","comme","mais"],answer:"car",sol:"«&nbsp;car&nbsp;» introduit une cause : Jeff se sauve parce qu'il a peur."},
  {q:"Complète la phrase suivante avec le <strong>marqueur de relation</strong> approprié. «&nbsp;Je voulais aller au cinéma ; _____, je n'avais plus d'argent.&nbsp;»",choices:["donc","cependant","ainsi","car"],answer:"cependant",sol:"«&nbsp;cependant&nbsp;» exprime une opposition/concession.",ai:true},

  // ── VOCABULAIRE ───────────────────────────────────────────────────
  {q:"Trouve l'<strong>antonyme</strong> de <em>belliqueux</em>.",choices:["Pacifique","Batailleur","Brillant","Ennuyeux"],answer:"Pacifique",sol:"Belliqueux = qui aime la guerre. Pacifique = qui aime la paix → antonyme."},
  {q:"Dans quelle phrase le mot <em>main</em> est-il utilisé au <strong>sens propre</strong>&nbsp;?",choices:["Il s'est fait prendre la main dans le sac.","Dominique a le cœur sur la main.","On met tous la main à la pâte.","Je lève la main pour répondre."],answer:"Je lève la main pour répondre.",sol:"Lever la main physiquement = sens littéral/propre. Les autres sont des expressions figurées."},
  {q:"Dans quelle phrase le mot «&nbsp;froid&nbsp;» est-il utilisé au <strong>sens figuré</strong>&nbsp;?",choices:["L'eau du lac est froide en janvier.","Il fait froid dehors ce matin.","Son accueil froid m'a surpris.","La glace fond quand il fait moins froid."],answer:"Son accueil froid m'a surpris.",sol:"«&nbsp;Accueil froid&nbsp;» = manque de chaleur humaine → sens figuré.",ai:true},
  {q:"Comment appelle-t-on la <strong>femelle du jars</strong>&nbsp;?",choices:["Une biche","Une génisse","Une oie","Une hase"],answer:"Une oie",sol:"Le jars est l'oie mâle ; la femelle s'appelle l'oie. Biche = femelle du cerf. Génisse = femelle du taureau. Hase = femelle du lièvre."},
  {q:"Comment appelle-t-on la <strong>femelle du bélier</strong>&nbsp;?",choices:["La vache","La brebis","La chèvre","La jument"],answer:"La brebis",sol:"Le bélier est le mouton mâle ; sa femelle est la brebis.",ai:true},
  {q:"Trouve l'<strong>antonyme</strong> de <em>redoutable</em>.",choices:["Admirable","Inoffensif","Effrayant","Magnifique"],answer:"Inoffensif",sol:"Redoutable = qui inspire la crainte. Inoffensif = qui ne présente aucun danger → antonyme.",ai:true},

  // ── PRÉFIXES / SUFFIXES ───────────────────────────────────────────
  {q:"Quel <strong>préfixe</strong> doit-on ajouter au verbe <em>prendre</em> pour lui donner le sens de «&nbsp;étonner&nbsp;»&nbsp;?",choices:["re-","dé-","sur-","mé-"],answer:"sur-",sol:"surprendre = étonner, déconcerter."},
  {q:"Quel <strong>préfixe</strong> donne le sens d'«&nbsp;opposition&nbsp;» ou de «&nbsp;contre&nbsp;»&nbsp;?",choices:["pré-","anti-","re-","sur-"],answer:"anti-",sol:"«&nbsp;Anti-&nbsp;» exprime l'opposition : antibiotique, antidote. «&nbsp;Pré-&nbsp;» = avant. «&nbsp;Re-&nbsp;» = encore. «&nbsp;Sur-&nbsp;» = au-dessus.",ai:true},
  {q:"Quel <strong>suffixe</strong> permet de former un nom à partir de l'adjectif «&nbsp;rapide&nbsp;»&nbsp;?",choices:["-ment","-ité","-eur","-age"],answer:"-ité",sol:"rapide + -ité = rapidité (nom désignant la qualité d'être rapide).",ai:true},

  // ── ORTHOGRAPHE ───────────────────────────────────────────────────
  {q:"Dans quelle phrase les <strong>homophones</strong> sont-ils bien orthographiés&nbsp;?",choices:["Colin à de la difficulté à mémoriser son texte.","Il a si peu dormi qu'il ne peut garder les yeux ouverts.","Jérémie et sont frère ne son pas dans notre équipe.","Je cherche mes livres, mais je ne les trouve pas."],answer:"Je cherche mes livres, mais je ne les trouve pas.",sol:"a) «&nbsp;à&nbsp;» devrait être «&nbsp;a&nbsp;» (verbe). b) «&nbsp;peu&nbsp;» devrait être «&nbsp;pu&nbsp;» (PP de pouvoir). c) «&nbsp;sont&nbsp;» et «&nbsp;son&nbsp;» sont inversés. d) mais ✓, les ✓."},
  {q:"Complète la phrase avec les mots appropriés. «&nbsp;Ils _____ sont rendus dans le parc _____ il y avait le spectacle.&nbsp;»",choices:["ce – ou","se – où","ce – où","se – ou"],answer:"se – où",sol:"«&nbsp;ils se sont rendus&nbsp;» (verbe pronominal). «&nbsp;le parc où&nbsp;» (pronom relatif de lieu) → se – où."},
  {q:"Quelle liste ne contient que des mots <strong>bien orthographiés</strong>&nbsp;?",choices:["grand, fracas, aromatique","remerciement, aboiement, vraiement","hébergement, savamment, apparaître","règlementaire, symptôme, crèche"],answer:"hébergement, savamment, apparaître",sol:"b) «&nbsp;vraiement&nbsp;» est incorrect (→ vraiment). c) hébergement ✓, savamment ✓, apparaître ✓."},
  {q:"Dans quelle phrase «&nbsp;a&nbsp;» et «&nbsp;à&nbsp;» sont-ils bien utilisés&nbsp;?",choices:["Il à beaucoup de travail à faire.","Il a beaucoup de travail a faire.","Il a beaucoup de travail à faire.","Il à beaucoup de travail a faire."],answer:"Il a beaucoup de travail à faire.",sol:"«&nbsp;a&nbsp;» = verbe avoir (remplaçable par «&nbsp;avait&nbsp;»). «&nbsp;à&nbsp;» = préposition.",ai:true},
  {q:"Parmi les mots invariables suivants, lequel peut être utilisé comme <strong>adverbe</strong>&nbsp;?",choices:["beau","vite","nouveau","long"],answer:"vite",sol:"«&nbsp;vite&nbsp;» est un adverbe (invariable). beau → belle, beaux ; nouveau → nouveaux ; long → longue.",ai:true},

  // ── NOMBRES EN LETTRES ────────────────────────────────────────────
  {q:"Comment s'écrivent les nombres <strong>41</strong> et <strong>91</strong> en lettres&nbsp;?",choices:["quarante et un, quatre-vingt-onze","quarante-et-un, quatre vingt onze","quarante et un, quatre-vingt onze","quarante-et-un, quatre-vingt-onze"],answer:"quarante et un, quatre-vingt-onze",sol:"«&nbsp;quarante et un&nbsp;» (sans trait d'union avec «&nbsp;et&nbsp;»). «&nbsp;quatre-vingt-onze&nbsp;» (avec traits d'union)."},

  // ── SUBORDONNÉE / PHRASE COMPLEXE ────────────────────────────────
  {q:"Dans la phrase «&nbsp;Le livre que tu m'as prêté est passionnant&nbsp;», quel est le rôle de la proposition «&nbsp;que tu m'as prêté&nbsp;»&nbsp;?",choices:["Elle est sujet.","Elle complète le nom «&nbsp;livre&nbsp;».","Elle est complément de phrase.","Elle est attribut du sujet."],answer:"Elle complète le nom «&nbsp;livre&nbsp;».",sol:"«&nbsp;que tu m'as prêté&nbsp;» est une subordonnée relative qui complète le nom «&nbsp;livre&nbsp;».",ai:true},
  {q:"Quelle phrase est à la <strong>forme passive</strong>&nbsp;?",choices:["Le chat mange la souris.","La souris est mangée par le chat.","La souris mange rapidement.","Le chat a mangé."],answer:"La souris est mangée par le chat.",sol:"Forme passive : sujet + auxiliaire être + PP + par + agent. «&nbsp;La souris&nbsp;» reçoit l'action.",ai:true},
  {q:"Laquelle de ces phrases est une phrase <strong>impérative</strong>&nbsp;?",choices:["Est-ce que tu viens avec nous&nbsp;?","Viens avec nous&nbsp;!","Tu viens avec nous.","Comme c'est gentil de venir avec nous&nbsp;!"],answer:"Viens avec nous&nbsp;!",sol:"La phrase impérative exprime un ordre ou une invitation. «&nbsp;Viens&nbsp;» est à l'impératif présent.",ai:true},

  // ── TYPE DE TEXTE ─────────────────────────────────────────────────
  {q:"Quel type de texte a pour but d'expliquer un phénomène ou de transmettre des connaissances&nbsp;?",choices:["Texte narratif","Texte descriptif","Texte informatif","Texte expressif"],answer:"Texte informatif",sol:"Le texte informatif vise à transmettre des connaissances ou à expliquer un phénomène.",ai:true},
];
